### ISSUE TITLE
Codeium Chat Window Goes Blank

### ISSUE THREAD

**Issue by tabish-javed** [Exafunction/codeium#72]
When clicked on settings tab inside codeium panel, everything there becomes invisible. There is no way of going back. Tried everything, even cleanup and re-install doesn't work. Attached is a screenshot for review.

![image](https://github.com/user-attachments/assets/c58981ca-919f-40d4-a60e-dee1288184b1)

**Comment by slashedstar** [comment]
Same here, at first it was asking to enable telemetry, after restarting vscode now its just blank
Fixed by uninstalling, deleting `C:\users\%user%\.codeium`, but then when I switch to the **Settings** tab it happens again (all codeium related settings in settings.json were deleted and it still happens)
Switching back to 1.10.1 fixed

**Comment by fortenforge** [comment]
1.10.6 fixes this.
